import "../globals.css";
import AuthContext from "@/src/context/AuthContext";
import ToasterContext from "@/src/context/ToaterContext";
import TopBar from "@/src/components/nav/TopBar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-stone-100 dark:bg-[#030303]">
        <AuthContext>
          <ToasterContext />
          <TopBar />
          <main className="flex flex-row">
            <section className="flex min-h-screen flex-1 flex-col items-center px-6 pb-10 pt-28 max-md:pb-32 sm:px-10">
              <div className="w-full max-w-4xl">{children}</div>
            </section>
          </main>
        </AuthContext>
      </body>
    </html>
  );
}
